version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    container_name: keycloak
    command: start
    environment:
      #KC_FEATURES: admin-fine-grained-authz,scripts,token-exchange,declarative-ui,dynamic-scopes,client-secret-rotation,recovery-codes,update-email,web-authn,account-api,account3,js-adapter,login2,multi-site,oid4vc-vci,organization,recovery-codes,device-flow
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - 8100:8080
    restart: always
    networks:
      - my_network
networks:
  my_network:
    name: my_network
    driver: bridge
