
name=demo_connector

connector.class=io.debezium.connector.cassandra.Cassandra3Connector

commit.log.relocation.dir=C:/Software/kafka_2.13-2.4.0/plugins/debezium/test_dir/relocation
offset.backing.store.dir=C:/Software/kafka_2.13-2.4.0/plugins/debezium/test_dir

http.port=8000
cassandra.commitlog.location=C:/Software/apache-cassandra-3.11.11/cdc/cdc_raw
cassandra.driver.config = C:/Software/kafka_2.13-2.4.0/plugins/debezium/driver.conf

cassandra.config=C:/Software/apache-cassandra-3.11.11/conf/cassandra.yaml
cassandra.hosts=localhost
cassandra.port=9042
cassandra.keyspace=my_keyspace

kafka.producer.bootstrap.servers=127.0.0.1:9092
kafka.producer.retries=3
kafka.producer.retry.backoff.ms=1000

topic.prefix=cassandra

key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false

value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

snapshot.consistency=ONE
snapshot.mode=ALWAYS
latest.commit.log.only=true
cassandra.schema.listener.class=io.debezium.connector.cassandra.Cassandra3SchemaChangeListener
cassandra.protocol.version:V4
tasks.max=1