version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    networks:
      - my_network
    environment:
      - DOCKER_HOST=tcp://docker:2376
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/santosh/dockervolumes/jenkins-data:/var/jenkins_home

networks:
  my_network:
    name: my_network
