version: '3.8'
services:
  es01:
    image: elasticsearch:8.14.3
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/santosh/dockervolumes/es/data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - my_network
    restart: always

  es02:
    image: elasticsearch:8.14.3
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/santosh/dockervolumes/es/data02:/usr/share/elasticsearch/data
    networks:
      - my_network
    restart: always

  es03:
    image: elasticsearch:8.14.3
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/santosh/dockervolumes/es/data03:/usr/share/elasticsearch/data
    networks:
      - my_network
    restart: always

  kibana:
    image: kibana:8.14.3
    container_name: kibana
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    networks:
      - my_network
    restart: always
    depends_on:
      - es01
      - es02
      - es03
    ports:
      - 5602:5601

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  my_network:
    name: my_network
    driver: bridge

