version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: netrix
      MYSQL_PASSWORD: netrix
    ports:
      - "3306:3306"
    volumes:
      - /home/santosh/dockervolumes/mysql_db_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
