version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"
    restart: always
    volumes:
      - "/home/santosh/docker_setup/ollama/.ollama:/root/.ollama"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    name: my_networks
