version: '3.8'
services:
  kowl:
    image: quay.io/cloudhut/kowl:master
    container_name: kafka_kowl
    environment:
      KAFKA_BROKERS: kafka_broker_0:9092
    networks:
      - my_network
    ports:
      - "9093:8080"
networks:
  my_network:
    name: my_network
    driver: bridge
