version: '3.8'

services:
  redis:
    image: redis:7.2.5
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/santosh/dockervolumes/redis-data:/data
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

